"""End-to-end smoke test for a fresh TheraEpiFlow install.

Seeds a minimal disposable project (HPV16 E7, 1 track) and runs every
pipeline step against it in non-interactive mode. Requires network access
for the IEDB API calls in predict_binding and consensus_filter.

Usage:
    conda activate TheraEpiFlow
    python tests/selftest.py

The test project is created under projects/bench_selftest/ and left on disk
so you can inspect intermediate files afterward. Re-running overwrites it.

Exit codes:
    0  — all steps completed with status 'done' or 'skipped'
    1  — at least one step errored or failed to import
"""

from __future__ import annotations

import os
import sys
import time
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

# Redirect stdin so all Rich prompts fall back to their default without blocking.
if sys.stdin.isatty():
    sys.stdin = open(os.devnull, "r")

from tests.validation.seed_project import seed_project, PRESETS   # noqa: E402
from tests.validation.run_replicate import run_replicate           # noqa: E402

PROJECT_NAME = "bench_selftest"
PRESET       = "hpv16_e7_tr1"


def _print_header(text: str) -> None:
    print(f"\n{'─' * 60}")
    print(f"  {text}")
    print(f"{'─' * 60}")


def main() -> None:
    _print_header("TheraEpiFlow — end-to-end self-test")
    print(f"Preset : {PRESET}")
    print(f"Project: {PROJECT_NAME}")
    print(f"Root   : {_REPO_ROOT}")

    # Step 1 — seed the project (overwrites any previous run).
    _print_header("1/2  Seeding project")
    seed_project(
        project_name=PROJECT_NAME,
        tracks=PRESETS[PRESET],
        description="Auto-generated by tests/selftest.py",
        overwrite=True,
    )
    print(f"Seeded projects/{PROJECT_NAME}/ — ready.")

    # Step 2 — run the full pipeline.
    _print_header("2/2  Running pipeline (network required for IEDB steps)")
    wall_start = time.perf_counter()
    report = run_replicate(PROJECT_NAME)
    wall_elapsed = time.perf_counter() - wall_start

    # Summarise.
    _print_header("Results")
    errors: list[str] = []
    for step_entry in report["steps"]:
        step_name = step_entry["step_name"]
        if step_entry.get("import_error"):
            print(f"  [IMPORT ERR]  {step_name}")
            errors.append(step_name)
            continue
        for run in step_entry["runs"]:
            tid     = run.get("track_id") or "global"
            status  = run.get("status", "?")
            elapsed = run.get("elapsed_seconds", 0)
            mark    = "OK " if status in ("done", "skipped") else "ERR"
            print(f"  [{mark}]  {step_name:<24} {tid:<12} {status:<8} {elapsed:>6.1f}s")
            if mark == "ERR":
                errors.append(f"{step_name} / {tid}: {run.get('error', '')}")

    print(f"\nTotal wall time: {wall_elapsed:.0f}s")

    if errors:
        print(f"\nFAILED — {len(errors)} error(s):")
        for e in errors:
            print(f"  • {e}")
        print("\nCheck TROUBLESHOOTING.md or run with verbose output for details.")
        sys.exit(1)
    else:
        print("\nAll steps passed. Installation is working correctly.")
        print(f"Open projects/{PROJECT_NAME}/data/output/REPORT_{PROJECT_NAME}.html in a browser.")
        sys.exit(0)


if __name__ == "__main__":
    main()
