"""Build one unified results workbook covering both validation experiments.

The thesis and the submission point reviewers at a single spreadsheet that
holds every number behind the figures: per-replicate timings (Experiment 1),
the timing summary, and the clinical-literature results (Experiment 2). It
carries one timing sheet per preset, a mean-total summary, and the Experiment 2
sheets, with no embedded charts (the PNGs already cover that), so the file
stands on its own as the user-facing reference table.

Sources (all under `results/`, regenerated by re-running the experiments):
  - `results/exp1/tables/exp1_timings_wide.csv`  -> per-preset timing sheets
  - `results/exp1/summary.json`                  -> timing summary
  - `results/exp2/summary.json`                  -> Experiment 2 timings
  - `results/exp2/iedb_hits.json`                -> literature support
  - `results/exp2/iedb_pmid_titles.csv`          -> supporting publications

Usage:
    python -m tests.validation.make_combined_table \\
        --exp1-root tests/validation/results/exp1 \\
        --exp2-root tests/validation/results/exp2 \\
        --out tests/validation/figures/exp_timings_wides_geral.xlsx
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

# Organism label shown next to each preset key in the summary sheet.
_PRESET_LABELS: dict[str, str] = {
    "hpv16_e7_tr1":    "E7 protein - HPV16 (1 track)",
    "hpv16_e7_tr3":    "E7 protein - HPV16 (3 tracks)",
    "sars_nucleo_tr1": "Nucleocapsid - SARS-CoV-2 (1 track)",
    "sars_nucleo_tr3": "Nucleocapsid - SARS-CoV-2 (3 tracks)",
}


def _read_json(path: Path) -> Optional[dict]:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def _overview_sheet() -> pd.DataFrame:
    """A plain-text sheet explaining what the workbook contains and how to redo it."""
    rows = [
        ("TheraEpiFlow validation results (Experiments 1 and 2)", ""),
        ("", ""),
        ("Experiment 1", "Execution time and reproducibility. Four disposable presets "
                         "(HPV16_E7 and SARS_NCAP, each at 1 and 3 tracks), 10 serial "
                         "replicates each. Each track is deterministic across replicates; "
                         "the only variation is the ~6% of IEDB NetMHCpan calls that return "
                         "a transient anomaly, which the pipeline flags rather than accepts."),
        ("Experiment 2", "Clinical literature validation. One 2-track project (HPV16_E7 + "
                         "SARS_NCAP), 10 serial replicates. Star peptides and a negative "
                         "control are queried against the IEDB IQ-API for T-cell and MHC-I "
                         "assays and supporting PMIDs."),
        ("", ""),
        ("Sheets", "Exp1_<preset>: raw per-replicate wall time per step. "
                   "Exp1_summary: median/IQR/min/max/mean per preset. "
                   "Exp2_timings: per-replicate wall time. "
                   "Exp2_literature_summary and _detail: IEDB hits per peptide. "
                   "Exp2_PMIDs: supporting publications."),
        ("", ""),
        ("Reproduce", "python -m tests.validation.run_experiment_1   (about 12 h serial)"),
        ("", "python -m tests.validation.run_experiment_2   (about 6 h)"),
        ("", "Then: make_charts.py, make_report.py, make_combined_table.py"),
        ("Quick demo", "A guided single-protein demo (HPV16_E7) is available from the "
                       "main.py menu (type 'demo'); it runs the whole pipeline end to end "
                       "in about 75 s and doubles as an environment check."),
    ]
    return pd.DataFrame(rows, columns=["Section", "Description"])


def _exp1_timing_frames(exp1_root: Path) -> dict[str, pd.DataFrame]:
    """One frame per preset from the wide timings CSV, keyed by preset."""
    csv_path = exp1_root / "tables" / "exp1_timings_wide.csv"
    if not csv_path.exists():
        return {}
    wide = pd.read_csv(csv_path)
    # Keep only columns that belong to the current pipeline.
    wide = wide.drop(columns=[c for c in wide.columns if "export_bundle" in c], errors="ignore")
    return {preset: group.reset_index(drop=True) for preset, group in wide.groupby("preset")}


def _exp1_summary_frame(exp1_root: Path) -> pd.DataFrame:
    """Per-preset median/IQR/min/max/mean of total wall time."""
    summary = _read_json(exp1_root / "summary.json")
    if not summary:
        return pd.DataFrame()
    presets: dict[str, list[float]] = {}
    for replicate in summary.get("replicates", []):
        total = replicate.get("total_seconds")
        if total is not None:
            presets.setdefault(replicate["preset_key"], []).append(float(total))

    rows = []
    for preset_key, totals in presets.items():
        arr = np.array(totals)
        rows.append({
            "preset":     preset_key,
            "label":      _PRESET_LABELS.get(preset_key, preset_key),
            "n":          int(arr.size),
            "median_s":   round(float(np.median(arr)), 2),
            "p25_s":      round(float(np.percentile(arr, 25)), 2),
            "p75_s":      round(float(np.percentile(arr, 75)), 2),
            "min_s":      round(float(arr.min()), 2),
            "max_s":      round(float(arr.max()), 2),
            "mean_s":     round(float(arr.mean()), 2),
            "mean_min":   round(float(arr.mean()) / 60, 2),
        })
    return pd.DataFrame(rows)


def _exp2_timing_frame(exp2_root: Path) -> pd.DataFrame:
    summary = _read_json(exp2_root / "summary.json")
    if not summary:
        return pd.DataFrame()
    rows = [
        {
            "replicate":     rec.get("project_name"),
            "total_seconds": rec.get("total_seconds"),
            "total_minutes": round(rec["total_seconds"] / 60, 2) if rec.get("total_seconds") else None,
            "step_errors":   rec.get("step_error_count", 0),
        }
        for rec in summary.get("replicates", [])
    ]
    return pd.DataFrame(rows)


def _exp2_literature_frames(exp2_root: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Return (summary, detail) frames from iedb_hits.json."""
    iedb = _read_json(exp2_root / "iedb_hits.json")
    if not iedb:
        return pd.DataFrame(), pd.DataFrame()

    summary_rows, detail_rows = [], []
    for track_id, payload in iedb.get("tracks", {}).items():
        stars = payload.get("star", [])
        negatives = payload.get("negative_control", [])

        def _with_hits(records):
            return sum(1 for r in records
                       if (r.get("tcell_assay_count", 0) + r.get("mhc_assay_count", 0)) > 0)

        summary_rows.append({
            "track":                 track_id,
            "star_unique":           len(stars),
            "star_with_hits":        _with_hits(stars),
            "neg_control_unique":    len(negatives),
            "neg_control_with_hits": _with_hits(negatives),
        })

        for category, records in (("star", stars), ("negative_control", negatives)):
            for r in records:
                tcell = r.get("tcell_assay_count", 0)
                mhc = r.get("mhc_assay_count", 0)
                detail_rows.append({
                    "track":             track_id,
                    "category":          category,
                    "peptide":           r.get("peptide"),
                    "tcell_assay_count": tcell,
                    "mhc_assay_count":   mhc,
                    "total_assays":      tcell + mhc,
                    "presence_count":    r.get("presence_count"),
                })

    detail = pd.DataFrame(detail_rows)
    if not detail.empty:
        detail = detail.sort_values(["track", "category", "total_assays"],
                                    ascending=[True, True, False]).reset_index(drop=True)
    return pd.DataFrame(summary_rows), detail


def build_workbook(exp1_root: Optional[Path], exp2_root: Optional[Path], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
        _overview_sheet().to_excel(writer, sheet_name="Overview", index=False)

        if exp1_root:
            for preset_key, frame in _exp1_timing_frames(exp1_root).items():
                # Sheet names cap at 31 chars; the preset keys are short enough.
                frame.to_excel(writer, sheet_name=f"Exp1_{preset_key}"[:31], index=False)
            summary = _exp1_summary_frame(exp1_root)
            if not summary.empty:
                summary.to_excel(writer, sheet_name="Exp1_summary", index=False)

        if exp2_root:
            exp2_timing = _exp2_timing_frame(exp2_root)
            if not exp2_timing.empty:
                exp2_timing.to_excel(writer, sheet_name="Exp2_timings", index=False)
            lit_summary, lit_detail = _exp2_literature_frames(exp2_root)
            if not lit_summary.empty:
                lit_summary.to_excel(writer, sheet_name="Exp2_literature_summary", index=False)
            if not lit_detail.empty:
                lit_detail.to_excel(writer, sheet_name="Exp2_literature_detail", index=False)
            pmid_csv = exp2_root / "iedb_pmid_titles.csv"
            if pmid_csv.exists():
                pd.read_csv(pmid_csv).to_excel(writer, sheet_name="Exp2_PMIDs", index=False)

    print(f"Combined workbook written to {out_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exp1-root", type=Path, default=Path("tests/validation/results/exp1"))
    parser.add_argument("--exp2-root", type=Path, default=Path("tests/validation/results/exp2"))
    parser.add_argument("--out", type=Path,
                        default=Path("tests/validation/figures/exp_timings_wides_geral.xlsx"))
    args = parser.parse_args()
    build_workbook(args.exp1_root, args.exp2_root, args.out)


if __name__ == "__main__":
    main()
